# Generated by Django 4.0.1 on 2022-01-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='image',
            field=models.ImageField(blank=True, db_column='image', default='Static/images/placeholder.png', null=True, upload_to='Static/images'),
        ),
    ]
