# Generated by Django 4.0.1 on 2022-01-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='image',
            field=models.ImageField(blank=True, db_column='image', null=True, upload_to='Static/images'),
        ),
    ]
